//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreServiceHost.HeroDbService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Interfaces.DbService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HeroDbService.IHeroDbService")]
    public interface IHeroDbService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroDbService/GetData", ReplyAction="http://tempuri.org/IHeroDbService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroDbService/GetData", ReplyAction="http://tempuri.org/IHeroDbService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroDbService/DbProjectServiceCall", ReplyAction="http://tempuri.org/IHeroDbService/DbProjectServiceCallResponse")]
        string DbProjectServiceCall();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroDbService/DbProjectServiceCall", ReplyAction="http://tempuri.org/IHeroDbService/DbProjectServiceCallResponse")]
        System.Threading.Tasks.Task<string> DbProjectServiceCallAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroDbService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IHeroDbService/GetDataUsingDataContractResponse")]
        CoreServiceHost.HeroDbService.CompositeType GetDataUsingDataContract(CoreServiceHost.HeroDbService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroDbService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IHeroDbService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<CoreServiceHost.HeroDbService.CompositeType> GetDataUsingDataContractAsync(CoreServiceHost.HeroDbService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroDbService/SayHello", ReplyAction="http://tempuri.org/IHeroDbService/SayHelloResponse")]
        void SayHello(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroDbService/SayHello", ReplyAction="http://tempuri.org/IHeroDbService/SayHelloResponse")]
        System.Threading.Tasks.Task SayHelloAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHeroDbServiceChannel : CoreServiceHost.HeroDbService.IHeroDbService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HeroDbServiceClient : System.ServiceModel.ClientBase<CoreServiceHost.HeroDbService.IHeroDbService>, CoreServiceHost.HeroDbService.IHeroDbService {
        
        public HeroDbServiceClient() {
        }
        
        public HeroDbServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HeroDbServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HeroDbServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HeroDbServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string DbProjectServiceCall() {
            return base.Channel.DbProjectServiceCall();
        }
        
        public System.Threading.Tasks.Task<string> DbProjectServiceCallAsync() {
            return base.Channel.DbProjectServiceCallAsync();
        }
        
        public CoreServiceHost.HeroDbService.CompositeType GetDataUsingDataContract(CoreServiceHost.HeroDbService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<CoreServiceHost.HeroDbService.CompositeType> GetDataUsingDataContractAsync(CoreServiceHost.HeroDbService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public void SayHello(string name) {
            base.Channel.SayHello(name);
        }
        
        public System.Threading.Tasks.Task SayHelloAsync(string name) {
            return base.Channel.SayHelloAsync(name);
        }
    }
}
